"""fresh

Revision ID: a87d65f54057
Revises: 
Create Date: 2021-07-03 16:08:06.369924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a87d65f54057'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('gender', sa.String(length=16), nullable=False),
    sa.Column('online', sa.Boolean(), nullable=False),
    sa.Column('paramaters', sa.Text(), nullable=False),
    sa.Column('location', sa.String(length=128), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('work_related', sa.Text(), nullable=False),
    sa.Column('about_me', sa.Text(), nullable=False),
    sa.Column('hobbies', sa.Text(), nullable=False),
    sa.Column('profile_image', sa.String(length=256), nullable=False),
    sa.Column('background_image', sa.String(length=256), nullable=False),
    sa.Column('facebook', sa.String(length=128), nullable=False),
    sa.Column('spotify', sa.String(length=128), nullable=False),
    sa.Column('youtube', sa.String(length=128), nullable=False),
    sa.Column('twitter', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
